name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: openwrt-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./autogen.sh

    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make

